# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('ref_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
