# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('signer', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('validity_date', models.DateField()),
                ('tax', models.CharField(max_length=50)),
                ('available_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('start_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('position', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=100, unique=True)),
                ('quota_date', models.DateField()),
                ('quota_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('position', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('fund_type', models.CharField(choices=[('RF', 'Renda Fixa'), ('MM', 'Multimercado'), ('FI', 'Fundo Imobiliário')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('person', models.CharField(max_length=150)),
            ],
        ),
    ]
