# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.CharField(max_length=9)),
                ('sector', models.CharField(max_length=100)),
                ('subSector', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('market_segment', models.CharField(max_length=100)),
                ('listing_segment', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('majority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.Stock')),
            ],
        ),
    ]
