# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
