# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentfund',
            name='quota_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
    ]
