# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20171010_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=9, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField()),
            ],
        ),
    ]
