# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SEL', 'Sell'), ('DIV', 'Dividends'), ('SPL', 'Split'), ('AGR', 'Aggregation')], max_length=3, null=True),
        ),
    ]
