# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='domain_url',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='schema_name',
        ),
    ]
