# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_auto_20170622_2345'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
