# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbapUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=14)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.CharField(blank=True, max_length=3, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.System')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
