# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('L', 'Low'), ('H', 'High'), ('VH', 'Very High')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
